application: poke-search
version: 1-10 #1.10.0
runtime: python
api_version: 1

handlers:
- url: /clearmem
  script: clearmemcache.py
  login: admin
- url: /styles/
  static_dir: styles
- url: /scripts/
  static_dir: scripts
- url: /images/
  static_dir: images

- url: /.*
  script: main.py
